/*
	2009-2013 VieCode
 @license	VieCode Commercial License <http://www.viecode.com/licence/commercial/>
 @package	com.viecode.marketplace
 @category	Marketplace
*/
var Marketplace={Category:{}};
Marketplace.Category.MarkAllAsRead=Class.extend({_proxy:null,init:function(){this._proxy=new WCF.Action.Proxy({success:$.proxy(this._success,this)});$(".markAllAsReadButton").click($.proxy(this._click,this))},_click:function(){this._proxy.setOption("data",{actionName:"markAllAsRead",className:"marketplace\\data\\category\\MarketplaceCategoryAction"});this._proxy.sendRequest()},_success:function(a,b,c){$(".marketplaceCategoryList").find(".badge").hide();$(".marketplaceEntryList .newMessageBadge").hide();$("#mainMenu .active .badge").hide();
$(".navigation").find(".badge.badgeUpdate").hide()}});
Marketplace.Category.AutoSelectParents=Class.extend({init:function(){$('.categoryListItem input[type="checkbox"]').change($.proxy(this._click,this))},_click:function(a){this._handleSelect($(a.currentTarget))},initDefaultSelection:function(a){this._handleSelect($("#categoryListItem"+a))},_handleSelect:function(a){if(a.is(":checked")){var b=a.data("path");$('.categoryListItem input[type="checkbox"]').each(function(a,d){0==b.indexOf($(d).data("path"))&&$(d).prop("checked",!0)})}}});
Marketplace.Entry={};Marketplace.Entry.Delete=WCF.Action.Delete.extend({_redirectURL:"",init:function(a,b,c){this._super(a,b);this._redirectURL=c},_success:function(a,b,c){(new WCF.System.Notification(WCF.Language.get("marketplace.entry.delete.success"))).show($.proxy(function(){window.location=this._redirectURL},this))}});
Marketplace.Entry.Like=WCF.Like.extend({_getContainers:function(){return $("article")},_getObjectID:function(a){return this._containers[a].data("objectID")},_getWidgetContainer:function(a){return this._containers[a].find(".messageHeader")},_buildWidget:function(a,b,c,d,e){var f=this._getWidgetContainer(a);if(this._canLike){var g=this._containers[a].find(".smallButtons");b.insertBefore(g.find(".toTopLink"));c.insertBefore(g.find(".toTopLink"));c.find("a").addClass("button");b.find("a").addClass("button")}e&&
(e.appendTo(this._containers[a].find(".messageBody > .messageFooter")),e.addClass("messageFooterNote"));f.find(".permalink").after(d)},_setActiveState:function(a,b,c){a=a.find(".button").removeClass("active");b=b.find(".button").removeClass("active");1==c?a.addClass("active"):-1==c&&b.addClass("active")},_addWidget:function(a,b){}});
Marketplace.Entry.Preview=WCF.Popover.extend({_proxy:null,init:function(){this._super(".marketplaceEntryLink");this._proxy=new WCF.Action.Proxy({showLoadingOverlay:!1});WCF.DOMNodeInsertedHandler.addCallback("Marketplace.Entry.Preview",$.proxy(this._initContainers,this))},_loadContent:function(){var a=$("#"+this._activeElementID);this._proxy.setOption("data",{actionName:"getEntryPreview",className:"marketplace\\data\\entry\\EntryAction",objectIDs:[a.data("entryID")]});var b=this._activeElementID,
c=this;this._proxy.setOption("success",function(a,e,f){c._insertContent(b,a.returnValues.template,!0)});this._proxy.sendRequest()}});
Marketplace.Entry.Create=Class.extend({init:function(a){$("#marketplaceCreateSubmit").click(function(b){""!=$("#price").val().trim()||a?null!=$("#price").val().trim().match(/^[0-9]+$/)&&(b.preventDefault(),WCF.System.Confirmation.show(WCF.Language.get("marketplace.entry.price.warning.onlyNumeric"),function(a){"confirm"==a&&$("#messageContainer").submit()})):(b.preventDefault(),WCF.System.Confirmation.show(WCF.Language.get("marketplace.entry.price.warning.empty"),function(a){"confirm"==a&&$("#messageContainer").submit()}))})}});
Marketplace.Entry.Offer=Class.extend({_buttons:{},_buttonSelector:"",_dialog:null,_notification:null,_objectID:0,_userID:0,_proxy:null,init:function(a){this._buttonSelector=a;this._buttons={};this._notification=null;this._objectID=0;this._proxy=new WCF.Action.Proxy({success:$.proxy(this._success,this)});this._initButtons()},_initButtons:function(){var a=this;$(this._buttonSelector).each(function(b,c){var d=$(c),e=d.wcfIdentify();a._buttons[e]||(a._buttons[e]=d,d.click($.proxy(a._click,a)))})},_click:function(a){this._objectID=
$(a.currentTarget).data("objectID");this._userID=$(a.currentTarget).data("userID");this._proxy.setOption("data",{actionName:"prepareOffer",className:"marketplace\\data\\offer\\OfferAction",parameters:{objectID:this._objectID,userID:this._userID}});this._proxy.sendRequest()},_success:function(a,b,c){a.returnValues.saved?(null===this._notification&&(this._notification=new WCF.System.Notification(WCF.Language.get("marketplace.entry.offer.success"))),this._dialog.wcfDialog("close"),this._notification.show()):
a.returnValues.template&&(this._showDialog(a.returnValues.template),a.returnValues.alreadyWarned||this._dialog.find(".jsSubmitWarning").click($.proxy(this._submit,this)))},_showDialog:function(a){null===this._dialog&&(this._dialog=$("#marketplaceOfferDialog"),this._dialog.length||(this._dialog=$('<div id="marketplaceOfferDialog" />').hide().appendTo(document.body)));this._dialog.html(a).wcfDialog({title:WCF.Language.get("marketplace.entry.offer")}).wcfDialog("render")},_submit:function(){this._proxy.setOption("data",
{actionName:"offer",className:"marketplace\\data\\offer\\OfferAction",parameters:{reason:$("#offerReason").val().trim(),price:$("#offerPrice").val().trim(),objectID:this._objectID,userID:this._userID}});this._proxy.sendRequest()}});
Marketplace.Entry.OfferDialog=Class.extend({_checkTypeAccept:null,_checkTypeNewOffer:null,init:function(){this._checkTypeAccept=$("#marketplaceOfferTypeAccept");this._checkTypeNewOffer=$("#marketplaceOfferTypeNewOffer");this._checkTypeAccept.change($.proxy(this._changeState,this));this._checkTypeNewOffer.change($.proxy(this._changeState,this))},_changeState:function(){this._checkTypeNewOffer.prop("checked")?($("#marketplaceOfferPrice").show(),$("#marketplaceOfferPrice").find("input").prop("required",
"required")):($("#marketplaceOfferPrice").hide(),$("#marketplaceOfferPrice").find("input").prop("required",""))}});
Marketplace.Entry.OfferManagement=Class.extend({_proxy:null,_objectID:0,_entryID:0,_type:"",_notification:null,init:function(){this._proxy=new WCF.Action.Proxy({success:$.proxy(this._success,this)});$(".manageOfferButton").click($.proxy(this._click,this))},_click:function(a){this._objectID=$(a.currentTarget).data("objectID");this._type=$(a.currentTarget).data("type");this._entryID=$(a.currentTarget).data("entryID");this._proxy.setOption("data",{actionName:"manage",className:"marketplace\\data\\offer\\OfferAction",
parameters:{objectID:this._objectID,status:this._type}});this._proxy.sendRequest()},_success:function(a,b,c){"accepted"==this._type&&($(".offerBadge_declined"+this._entryID).show(),$("#offerBadge_declined"+this._objectID).hide(),$(".manageOfferButtonEntry"+this._entryID).hide(),$("#marketplaceEntry"+this._entryID).addClass("marketplaceEntryStatusComplete"),$("#marketplaceEntryLabelList"+this._entryID).show());$("#offerBadge_"+this._type+this._objectID).show();$(".manageOfferButton"+this._objectID).hide();
null===this._notification&&(this._notification=new WCF.System.Notification(WCF.Language.get("marketplace.entry.offer.success."+this._type)));this._notification.show()}});
Marketplace.Entry.CompletedDetail=Class.extend({init:function(){$(".marketplaceEntryStatusComplete a").click(this._stop);$(".marketplaceEntryStatusComplete input").click(this._stop);$(".marketplaceEntryStatusComplete").click(this._click)},_click:function(a){a=$(a.currentTarget).find(".marketplaceMessageBodyCompletedItem");a.hasClass("marketplaceMessageBodyCompleted")?a.removeClass("marketplaceMessageBodyCompleted"):a.addClass("marketplaceMessageBodyCompleted")},_stop:function(a){$(a.currentTarget).hasClass("jsEntryInlineEditor")||
a.stopImmediatePropagation()}});Marketplace.Entry.LargeMap=WCF.Location.GoogleMaps.LargeMap.extend({});
Marketplace.Entry.MapNearbySearch=Class.extend({_checkTypeAuto:null,_checkTypeAddress:null,init:function(){this._checkTypeAuto=$("#marketplaceMapTypeAuto");this._checkTypeAddress=$("#marketplaceMapTypeAddress");this._checkTypeAuto.change($.proxy(this._changeState,this));this._checkTypeAddress.change($.proxy(this._changeState,this));navigator.geolocation&&navigator.geolocation.getCurrentPosition($.proxy(this._updateLocation,this))},_changeState:function(){this._checkTypeAddress.prop("checked")?$(".marketplaceAddressForm").show():
$(".marketplaceAddressForm").hide()},_updateLocation:function(a){a.coords.latitude&&a.coords.longitude&&($("#marketplaceMapSearchType").show(),this._checkTypeAddress.prop("checked",!1),this._checkTypeAuto.prop("checked",!0),$("#mapSearchLat").val(a.coords.latitude),$("#mapSearchLng").val(a.coords.longitude),geocoder=new google.maps.Geocoder,geocoder.geocode({latLng:new google.maps.LatLng(a.coords.latitude,a.coords.longitude)},function(a,c){if(c==google.maps.GeocoderStatus.OK){var d=$("#marketplaceMapTypeAutoLabel");
a[0]&&d.html(d.html()+" ("+a[0].formatted_address+")")}}),this._changeState())}});
Marketplace.Entry.Clipboard=Class.extend({_updateHandler:null,init:function(a){this._updateHandler=a;$(".jsClipboardEditor").each($.proxy(function(a,c){var d=$(c),e=eval(d.data("types"));if(WCF.inArray("com.viecode.marketplace.entry",e))return d.on("clipboardAction",$.proxy(this._execute,this)),d.on("clipboardActionResponse",$.proxy(this._evaluateResponse,this)),!1},this))},_execute:function(a,b,c,d){},_evaluateResponse:function(a,b,c,d,e){if("com.viecode.marketplace.entry"===c&&b.returnValues.entryData&&
$.getLength(b.returnValues.entryData))for(var f in b.returnValues.entryData)this._updateHandler.update(f,b.returnValues.entryData[f])}});
Marketplace.Entry.UpdateHandler=Class.extend({_entries:{},_redirectURL:"",init:function(){var a=this;$(".marketplaceEntry").each(function(b,c){var d=$(c);a._entries[d.data("entryID")]=d})},update:function(a,b){if(this._entries[a])for(var c in b)this._updateProperty(a,c,b[c]);else console.debug("[Marketplace.Entry.UpdateHandler] Unknown entry id "+a)},_updateProperty:function(a,b,c){switch(b){case "deleted":this._delete(a,c);break;case "deleteNote":this._deleteNote(a,c);break;case "isDisabled":c?this._disable(a):
this._enable(a);break;case "isDone":c?this._done(a):this._undone(a);break;case "commentsEnabled":c?this._disableComments(a):this._enableComments(a);break;default:this._handleCustomProperty(a,b,c)}},_handleCustomProperty:function(a,b,c){this._entries[a].trigger("entryUpdateHandlerProperty",[a,b,c])},_delete:function(a,b){this._redirectURL?window.location=this._redirectURL:this._entries[a].hide()},_deleteNote:function(a,b){},_disable:function(a){this._entries[a].data("isDisabled",1);this._entries[a].find(".marketplaceStatusIcon").attr("class",
"marketplaceStatusIcon icon-lock");this._entries[a].find(".marketplaceStatusIcon").attr("title",WCF.Language.get("marketplace.entry.status.disabled"))},_disableComments:function(a){this._entries[a].data("enableComments",0);$(".marketplaceEntryComments").hide()},_done:function(a){this._entries[a].data("isDone",1);this._entries[a].addClass("marketplaceEntryStatusComplete");this._entries[a].find(".marketplaceStatusIcon").attr("class","marketplaceStatusIcon icon-ok-circle");this._entries[a].find(".marketplaceStatusIcon").attr("title",
WCF.Language.get("marketplace.entry.status.completed"));this._entries[a].find(".marketplaceMessageBody").addClass("marketplaceMessageBodyCompletedItem marketplaceMessageBodyCompleted");this._entries[a].find(".marketplaceEntryIncompleteLabel").hide();this._entries[a].find(".marketplaceEntryCompleteLabel").show()},_enable:function(a){this._entries[a].data("isDisabled",0);this._restoreIcon(a)},_enableComments:function(a){this._entries[a].data("enableComments",1);$(".marketplaceEntryComments").hide()},
_undone:function(a){this._entries[a].data("isDone",0);this._restoreIcon(a);this._entries[a].removeClass("marketplaceEntryStatusComplete");this._entries[a].find(".marketplaceMessageBody").removeClass("marketplaceMessageBodyCompletedItem marketplaceMessageBodyCompleted");this._entries[a].find(".marketplaceEntryIncompleteLabel").show();this._entries[a].find(".marketplaceEntryCompleteLabel").hide()},_restoreIcon:function(a){switch(this._entries[a].data("type")){case "search":this._entries[a].find(".marketplaceStatusIcon").attr("class",
"marketplaceStatusIcon icon-search");this._entries[a].find(".marketplaceStatusIcon").attr("title",WCF.Language.get("marketplace.entry.status.search"));break;case "offer":this._entries[a].find(".marketplaceStatusIcon").attr("class","marketplaceStatusIcon icon-legal");this._entries[a].find(".marketplaceStatusIcon").attr("title",WCF.Language.get("marketplace.entry.status.offer"));break;case "exchange":this._entries[a].find(".marketplaceStatusIcon").attr("class","marketplaceStatusIcon icon-exchange");
this._entries[a].find(".marketplaceStatusIcon").attr("title",WCF.Language.get("marketplace.entry.status.exchange"));break;case "expired":this._entries[a].find(".marketplaceStatusIcon").attr("class","marketplaceStatusIcon icon-time");this._entries[a].find(".marketplaceStatusIcon").attr("title",WCF.Language.get("marketplace.entry.status.expired"));break;case "completed":this._entries[a].find(".marketplaceStatusIcon").attr("class","marketplaceStatusIcon icon-ok-circle"),this._entries[a].find(".marketplaceStatusIcon").attr("title",
WCF.Language.get("marketplace.entry.status.completed"))}},getValue:function(a,b){if(!this._entries[a])return console.debug("[Marketplace.Entry.UpdateHandler] Unknown entry id "+a),!1;switch(b){case "isDeleted":return this._entries[a].data("isDeleted");case "isDisabled":return this._entries[a].data("isDisabled");case "enableComments":return this._entries[a].data("enableComments");case "isDone":return this._entries[a].data("isDone")}},setRedirectURL:function(a){this._redirectURL=a}});
Marketplace.Entry.InlineEditor=WCF.InlineEditor.extend({_permissions:{},_updateHandler:null,_redirectEditURL:null,_setOptions:function(){this._options=[{label:WCF.Language.get("marketplace.entry.edit.done"),optionName:"done"},{label:WCF.Language.get("marketplace.entry.edit.undone"),optionName:"undone"},{label:WCF.Language.get("marketplace.entry.edit.enable"),optionName:"enable"},{label:WCF.Language.get("marketplace.entry.edit.disable"),optionName:"disable"},{label:WCF.Language.get("marketplace.entry.edit.comments.enable"),
optionName:"enableComments"},{label:WCF.Language.get("marketplace.entry.edit.comments.disable"),optionName:"disableComments"},{label:WCF.Language.get("marketplace.entry.edit.delete"),optionName:"delete"},{optionName:"divider"},{label:WCF.Language.get("marketplace.entry.edit.advanced"),optionName:"advanced"}]},setUpdateHandler:function(a){this._updateHandler=a},_getTriggerElement:function(a){return a.find(".jsEntryInlineEditor")},_validate:function(a,b){var c=$("#"+a).data("entryID");switch(b){case "delete":if(!this._getPermission("canDeleteEntry"))break;
return!this._updateHandler.getValue(c,"isDeleted");case "done":case "undone":if(!this._getPermission("canMarkAsDone"))break;return"undone"===b?this._updateHandler.getValue(c,"isDone"):!this._updateHandler.getValue(c,"isDone");case "disableComments":case "enableComments":if(!this._getPermission("canDisableComments"))break;return"disableComments"===b?this._updateHandler.getValue(c,"enableComments"):!this._updateHandler.getValue(c,"enableComments");case "enable":if(!this._getPermission("canEnableEntry"))break;
if(this._updateHandler.getValue(c,"isDeleted"))break;return this._updateHandler.getValue(c,"isDisabled");case "disable":if(!this._getPermission("canEnableEntry"))break;if(this._updateHandler.getValue(c,"isDeleted"))break;return!this._updateHandler.getValue(c,"isDisabled");case "advanced":if(!this._getPermission("canEditEntry"))break;return null!=this._redirectEditURL}return!1},_execute:function(a,b){if(!this._validate(a,b))return!1;switch(b){case "done":case "undone":this._updateEntry(a,b,{isDone:"done"===
b?1:0});break;case "enable":case "disable":this._updateEntry(a,b,{isDisabled:"enable"===b?0:1});break;case "enableComments":case "disableComments":this._updateEntry(a,b,{commentsEnabled:"enableComments"===b?0:1});break;case "delete":var c=this;WCF.System.Confirmation.show(WCF.Language.get("marketplace.entry.delete.sure"),function(d){"confirm"===d&&c._updateEntry(a,b,{deleted:1})});break;case "advanced":window.location=this._redirectEditURL;return;default:return!1}return!0},_updateEntry:function(a,
b,c){if("delete"===b){var d=this,e=this._elements[a].data("entryID");new WCF.Action.Proxy({autoSend:!0,data:{actionName:"delete",className:"marketplace\\data\\entry\\EntryAction",objectIDs:[e]},success:function(a){d._updateHandler.update(e,a.returnValues.entryData[e])}})}else this._updateData.push({data:c,elementID:a,optionName:b}),this._proxy.setOption("data",{actionName:b,className:"marketplace\\data\\entry\\EntryAction",objectIDs:[this._elements[a].data("entryID")],parameters:{data:c}}),this._proxy.sendRequest()},
_updateState:function(){this._notification.show();for(var a=0,b=this._updateData.length;a<b;a++){var c=this._updateData[a],d=$("#"+c.elementID).data("entryID");this._updateHandler.update(d,c.data)}},_getPermission:function(a){return this._permissions[a]?this._permissions[a]:0},setPermission:function(a,b){this._permissions[a]=b},setPermissions:function(a){for(var b in a)this.setPermission(b,a[b])},setRedirectEditURL:function(a){this._redirectEditURL=a}});
Marketplace.Entry.MarkAsRead=Class.extend({_proxy:null,init:function(){this._proxy=new WCF.Action.Proxy({success:$.proxy(this._success,this)});$(document).on("dblclick",".marketplaceEntryList .markAsRead",$.proxy(this._dblClick,this))},_dblClick:function(a){this._proxy.setOption("data",{actionName:"markAsRead",className:"marketplace\\data\\entry\\EntryAction",objectIDs:[$(a.currentTarget).parents("article:eq(0)").data("entryID")]});this._proxy.sendRequest()},_success:function(a,b,c){$(".marketplaceEntryList .markAsRead").each(function(b,
c){var f=$(c),g=f.parents("article:eq(0)");WCF.inArray(g.data("entryID"),a.objectIDs)&&(g.find(".newMessageBadge").remove(),f.removeClass("markAsRead"),f.unbind("dblclick"))})}});
Marketplace.Entry.ShareBBCode=Class.extend({_cache:{},_dialog:null,init:function(){this._cache={};this._dialog=null;this._initLinks();WCF.DOMNodeInsertedHandler.addCallback("WCF.Message.Share.Content",$.proxy(this._initLinks,this))},_initLinks:function(){$("a.jsMarketplaceBBCodeShare").removeClass("jsMarketplaceBBCodeShare").click($.proxy(this._click,this))},_click:function(a){a.preventDefault();a=$(a.currentTarget).data("entryID");if(void 0===this._cache[a]){var b=!1;null===this._dialog?(this._dialog=
$("<div />").hide().appendTo(document.body),b=!0):this._dialog.empty();var c=$('<fieldset><legend><label for="__shareBBCode">'+WCF.Language.get("wcf.message.share.permalink.bbcode")+"</label></legend></fieldset>").appendTo(this._dialog);$('<input type="text" id="__shareBBCode" class="long" readonly="readonly" />').attr("value","[marketplace]"+a+"[/marketplace]").appendTo(c);this._cache[a]=this._dialog.html();b?this._dialog.wcfDialog({title:WCF.Language.get("wcf.message.share")}):this._dialog.wcfDialog("open")}else this._dialog.html(this._cache[a]).wcfDialog("open");
this._dialog.find("input").click(function(){$(this).select()})}});
Marketplace.Entry.IPAddressHandler=Class.extend({_cache:{},_dialog:null,_proxy:null,init:function(){this._cache={};this._dialog=null;this._proxy=new WCF.Action.Proxy({success:$.proxy(this._success,this)});this._initButtons();WCF.DOMNodeInsertedHandler.addCallback("Marketplace.Entry.IPAddressHandler",$.proxy(this._initButtons,this))},_initButtons:function(){var a=this;$(".jsIpAddress").each(function(b,c){var d=$(c),e=d.data("entryID");void 0===a._cache[e]&&(a._cache[e]="",d.click($.proxy(a._click,
a)))})},_click:function(a){a=$(a.currentTarget).data("entryID");this._cache[a]?this._showDialog(a):(this._proxy.setOption("data",{actionName:"getIpLog",className:"marketplace\\data\\entry\\EntryAction",parameters:{entryID:a}}),this._proxy.sendRequest())},_success:function(a,b,c){this._cache[a.returnValues.entryID]=a.returnValues.template;this._showDialog(a.returnValues.entryID)},_showDialog:function(a){null===this._dialog&&(this._dialog=$("<div />").hide().appendTo(document.body));this._dialog.html(this._cache[a]);
this._dialog.wcfDialog({title:WCF.Language.get("marketplace.entry.ipAddress.title")});this._dialog.wcfDialog("render")}});
